//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas
    {
        public int CODIGO { get; set; }
        public string TITULO { get; set; }
        public string TEXTO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
